apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      serviceAccount: devops-sa 
      containers:
      - name: frontend
        image: us-east4-docker.pkg.dev/inner-root-434608-t5/d9xmsuperhit-frontend/d9xmsuperhit-frontend:1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://34.111.36.180:3500/api/tasks"
        ports:
        - containerPort: 3000
